#!/usr/bin/env python3
"""
gen_embed.py — Embed www/ web assets into payload/www_embed.h
Run from the repo root:
    python3 payload/tools/gen_embed.py
Re-run any time www/ files change so the ELF stays up-to-date.
"""

import os
import sys

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))
WWW_DIR   = os.path.join(REPO_ROOT, "www")
OUT_PATH  = os.path.join(REPO_ROOT, "payload", "www_embed.h")

# (relative path inside www/, URL served at, MIME type)
FILES = [
    ("index.html",   "/",            "text/html; charset=utf-8"),
    ("app.js",       "/app.js",      "application/javascript"),
    ("pkg.html",     "/pkg.html",    "text/html; charset=utf-8"),
    ("js/snow.js",   "/js/snow.js",  "application/javascript"),
    ("js/pkg.js",    "/js/pkg.js",   "application/javascript"),
]

def to_c_sym(name):
    return "embed_" + name.replace("/", "_").replace(".", "_").replace("-", "_")

def main():
    lines = [
        "/* AUTO-GENERATED by payload/tools/gen_embed.py — do not edit manually. */",
        "/* Run `python3 payload/tools/gen_embed.py` to regenerate.              */",
        "#ifndef WWW_EMBED_H",
        "#define WWW_EMBED_H",
        "#include <stddef.h>",
        "",
        "typedef struct {",
        "    const char         *url_path;",
        "    const char         *mime_type;",
        "    const unsigned char *data;",
        "    size_t              size;",
        "} embedded_file_t;",
        "",
    ]

    sym_table = []
    for fname, url, mime in FILES:
        fpath = os.path.join(WWW_DIR, fname)
        if not os.path.exists(fpath):
            print(f"WARN: {fpath} not found — skipping", file=sys.stderr)
            continue
        data = open(fpath, "rb").read()
        sym  = to_c_sym(fname)
        sym_table.append((sym, url, mime, len(data)))

        lines.append(f"/* {fname}  ({len(data):,} bytes) */")
        lines.append(f"static const unsigned char {sym}[] = {{")
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
        lines.append("};")
        lines.append("")

    lines.append("static const embedded_file_t g_embedded_files[] = {")
    for sym, url, mime, sz in sym_table:
        lines.append(f'    {{ "{url}", "{mime}", {sym}, {sz} }},')
    lines.append("};")
    lines.append(f"static const size_t g_embedded_file_count = {len(sym_table)};")
    lines.append("")
    lines.append("#endif /* WWW_EMBED_H */")

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")

    total = sum(sz for _, _, _, sz in sym_table)
    print(f"[gen_embed] {OUT_PATH}: {len(sym_table)} files embedded ({total:,} bytes)")

if __name__ == "__main__":
    main()
