#!/usr/bin/env python3
"""
gen_sfo_embed.py — Convert binary param.sfo → payload/sfo_embed.h C array.

Usage:
    python3 payload/tools/gen_sfo_embed.py <param.sfo> <sfo_embed.h>

Called automatically by CMakeLists.txt when sfo_embed.h is missing.
Run manually after editing param_sfo_config.json:
    python3 payload/tools/gen_param_sfo.py \\
        payload/sce_sys/param_sfo_config.json /tmp/param.sfo
    python3 payload/tools/gen_sfo_embed.py /tmp/param.sfo payload/sfo_embed.h
"""

import sys
import os

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <param.sfo> <sfo_embed.h>", file=sys.stderr)
        sys.exit(1)

    sfo_path = sys.argv[1]
    out_path = sys.argv[2]

    with open(sfo_path, "rb") as f:
        data = f.read()

    lines = [
        "/* AUTO-GENERATED by payload/tools/gen_sfo_embed.py — do not edit manually. */",
        "/* See payload/sce_sys/param_sfo_config.json to change app metadata.        */",
        "#ifndef SFO_EMBED_H",
        "#define SFO_EMBED_H",
        "#include <stddef.h>",
        "",
        f"/* Binary param.sfo ({len(data)} bytes) */",
        "static const unsigned char g_param_sfo_data[] = {",
    ]
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines += [
        "};",
        f"static const size_t g_param_sfo_size = {len(data)};",
        "",
        "#endif /* SFO_EMBED_H */",
    ]

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"[gen_sfo_embed] {out_path}: {len(data)} bytes")

if __name__ == "__main__":
    main()
