#!/usr/bin/env bash
# gen_pkg.sh — Package staging dir into a PS5 fake PKG (fPKG)
#
# Usage:
#   bash payload/tools/gen_pkg.sh <staging_dir> <output.pkg>
#
# The staging dir must contain:
#   eboot.bin              — compiled PS5 ELF (renamed)
#   sce_sys/param.sfo      — generated by gen_param_sfo.py
#   sce_sys/icon0.png      — 512x512 PNG icon
#
# This script uses orbis-pub-cmd (from the PS5 Payload SDK or OpenOrbis)
# to build the PKG. If orbis-pub-cmd is not available, it falls back to
# fp-pkg (https://github.com/xVoid879/fp-pkg) if that is on PATH.
#
# Install the resulting Quaza.pkg on your PS5 using GoldHEN Package
# Installer, ItemZz, or any compatible PKG installer.

set -euo pipefail

STAGING_DIR="${1:?Usage: gen_pkg.sh <staging_dir> <output.pkg>}"
OUTPUT_PKG="${2:?}"

echo "[gen_pkg] Staging dir : $STAGING_DIR"
echo "[gen_pkg] Output PKG  : $OUTPUT_PKG"

# Validate required files
for f in "$STAGING_DIR/eboot.bin" \
          "$STAGING_DIR/sce_sys/param.sfo" \
          "$STAGING_DIR/sce_sys/icon0.png"; do
    if [[ ! -f "$f" ]]; then
        echo "[gen_pkg] ERROR: Missing required file: $f" >&2
        exit 1
    fi
done

# Try orbis-pub-cmd first, then fp-pkg
if command -v orbis-pub-cmd &>/dev/null; then
    echo "[gen_pkg] Using orbis-pub-cmd..."
    orbis-pub-cmd img_create \
        --skip_digest \
        "$STAGING_DIR" \
        "$OUTPUT_PKG"

elif command -v fp-pkg &>/dev/null; then
    echo "[gen_pkg] Using fp-pkg..."
    fp-pkg pack "$STAGING_DIR" "$OUTPUT_PKG"

else
    echo "[gen_pkg] ERROR: Neither orbis-pub-cmd nor fp-pkg found on PATH." >&2
    echo "[gen_pkg] Install one of:" >&2
    echo "[gen_pkg]   orbis-pub-cmd — from the PS5 Payload SDK" >&2
    echo "[gen_pkg]   fp-pkg        — https://github.com/xVoid879/fp-pkg" >&2
    exit 1
fi

echo "[gen_pkg] Done → $OUTPUT_PKG"
echo "[gen_pkg] Install Quaza.pkg on your PS5 using GoldHEN Package Installer."
