#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <unistd.h>
#include <pthread.h>

#include "pkg_server.h"
#include "browser_launch.h"

/*
 * Quaza — PS5 PKG Tool
 * ====================
 * Entry point for the PS5 ELF payload.
 *
 * Startup sequence:
 *   1. Initialise the HTTP server (bind port PKG_SERVER_PORT).
 *   2. Spawn a background thread to keep the server running.
 *   3. Open the PS5 WebKit browser at http://127.0.0.1:<port>
 *      so the UI appears automatically when the app icon is clicked.
 *   4. Block until a signal (SIGINT / SIGTERM) tears everything down.
 *
 * App icon / game library integration:
 *   This ELF is packaged as a fake PKG (fPKG) using the tooling in
 *   payload/tools/.  See docs/INSTALL.md for the full build + install flow.
 *   The sce_sys/ folder inside the PKG provides the icon and metadata
 *   that the PS5 game library reads.
 *
 * Offline mode:
 *   All web assets (HTML / JS) are compiled directly into this ELF via
 *   payload/www_embed.h (generated by payload/tools/gen_embed.py).
 *   The HTTP server always tries embedded assets first, so the UI works
 *   even without any files on disk.
 */

static volatile int g_running = 1;

static void signal_handler(int sig) {
    (void)sig;
    g_running = 0;
    pkg_server_stop();
}

/* Server thread — wraps pkg_server_run() so we can launch the browser
 * from the main thread at the right moment. */
static void *server_thread(void *arg) {
    (void)arg;
    pkg_server_run();          /* blocks until pkg_server_stop() is called */
    return NULL;
}

int main(int argc, char **argv) {
    (void)argc; (void)argv;

    printf("╔══════════════════════════════════════╗\n");
    printf("║          Quaza  PS5 PKG Tool         ║\n");
    printf("║       Native Homebrew Payload        ║\n");
    printf("╚══════════════════════════════════════╝\n\n");

    signal(SIGINT,  signal_handler);
    signal(SIGTERM, signal_handler);

    /* ── 1. Initialise HTTP server ────────────────────────────────────── */
    printf("[main] Initialising HTTP server on port %d...\n", PKG_SERVER_PORT);
    if (pkg_server_init() < 0) {
        fprintf(stderr, "[main] Failed to initialise PKG server — aborting.\n");
        return 1;
    }
    printf("[main] Server ready.\n");

    /* ── 2. Start server on a background thread ──────────────────────── */
    pthread_t srv_tid;
    if (pthread_create(&srv_tid, NULL, server_thread, NULL) != 0) {
        fprintf(stderr, "[main] Failed to spawn server thread — aborting.\n");
        return 1;
    }

    /* ── 3. Auto-open browser ─────────────────────────────────────────── */
    char url[64];
    snprintf(url, sizeof(url), "http://127.0.0.1:%d", PKG_SERVER_PORT);
    printf("[main] Opening PS5 browser → %s\n", url);
    browser_launch(url);      /* non-fatal if it fails */

    /* ── 4. Wait for shutdown signal ─────────────────────────────────── */
    printf("[main] Quaza running — press the PS button to switch apps.\n");
    while (g_running) {
        sleep(1);
    }

    printf("[main] Shutting down...\n");
    pthread_join(srv_tid, NULL);
    printf("[main] Done.\n");
    return 0;
}
